### ISSUE TITLE
32-bit wav

### ISSUE THREAD

**Issue by nihilazo** [hamiltron/py-simple-audio#10]
Would it be possible to include support for 32-bit wave files for WaveObjects?

**Comment by hamiltron** [comment]
I think this (and 24-bit audio) would be great future milestones. As of this writing, I have limited time I can spend on the project so I probably won't be diving into this soon. However, for the sake of discussion, here are some things that would need to be investigated:
* What variation (if any) exists for 32-bit WAV files
* How the [wave module](https://docs.python.org/3/library/wave.html) handles them
* Variation in OS-specific format specification API's

Important to note is that simpleaudio is intended to as platform agnostic as possible with its public API. Therefore the plan is to err on the side of not implementing features that won't be possible on one of the supported platforms. If implementing 24- or 32-bit audio meets this general criterion, then it is worth pursuing.

**Comment by hiccup7** [comment]
I have been using digital audio workstation (DAW) software and a lot of audio players and utilities for many years, and every 32-bit WAV file I have seen has been floating-point.  Few software apps even handle 32-bit PCM WAV files.  Python's standard library wave module simply does not support floating-point WAV files.  To keep simpleaudio dependency-free, I don't see how 32-bit (floating-point.) WAV files could be supported.

Python's standard library wave module does support 24-bit WAV files.  However, simpleaudio's goal of being cross-platform would be more complex because the default sound output device does not always support 24-bit.  16-bit is the lowest common denominator.  Does @hamiltron want to add the complexity of querying the sound output device to see if it handles 24-bit and converting 24-bit WAV data to 16-bit when necessary?

Users have the option of converting 24-bit WAV files to 16-bit with an external utility.  Users also have the option of using this package: http://www.lfd.uci.edu/~gohlke/pythonlibs/#sounddevice
It can be as simple to use as simpleaudio, but it is also very flexible.  It's dependencies are already included in scientific Python distributions like WinPython and Anaconda.

**Comment by hamiltron** [comment]
Thanks for the comments, @hiccup7! Good to have some input from experience. Here are some thoughts (mostly for reference for when I look at this again)... 
* Since the Python's wave module supports 24-bit, it would make sense to work toward support of native 24-bit playback. At this point, it would probably start with an optimistic attempt to play and error of the OS doesn't support it. 
* Native floating point doesn't seem worth the effort at this point, especially since actual hardware (DAC) support is probably quite rare/expensive. However, an independent module could handle reading such files at the binary level and turn them into objects in a similar manner to the wave module that can be bit-crushed or otherwise processed. 
* It might be worth looking at including an additional utility submodule (or maybe just a separate package) to do sample-size conversion. That way the playback interface can still have sample size explicitly specified but handling multiple formats with limited audio interfaces would be easier.

**Comment by hamiltron** [comment]
24-bit and 32-bit support has been added. Upon further investigation, it became clear that the audio engines across all three OS's support both in a handful of ways (with conversion being apparently done in software layers) and there was enough overlap in supported formats to allow 'packed' 24-bit integer audio and 32-bit floating point audio. See updated docs for some example of how to handle 24-bit audio.
